.PHONY : ALL
ALL : t7.2 t7.3.1 t7.3.2 t7.4 t7.5 t7.5.1 t7.5.2 t7.8 t7.9 t7.10 t7.11

t7.2 : t7.2.c
	gcc -std=c99 -Wall t7.2.c -o t7.2

t7.3.1 : t7.3.1.c
	gcc -std=c99 -Wall t7.3.1.c -o t7.3.1

t7.3.2 : t7.3.2.c
	gcc -std=c99 -Wall t7.3.2.c -o t7.3.2

t7.4 : t7.4.c
	gcc -std=c99 -Wall t7.4.c -o t7.4

t7.5 : t7.5.c
	gcc -std=c99 -Wall t7.5.c -o t7.5

t7.5.1 : t7.5.1.c
	gcc -std=c99 -Wall t7.5.1.c -o t7.5.1

t7.5.2 : t7.5.2.c
	gcc -std=c99 -Wall t7.5.2.c -o t7.5.2

t7.8 : t7.8.c
	gcc -std=c99 -Wall t7.8.c -o t7.8

t7.9 : t7.9.c
	gcc -std=c99 -Wall t7.9.c -o t7.9

t7.10 : t7.10.c
	gcc -std=c99 -Wall -o t7.10 t7.10.c

t7.11 : t7.11.c
	gcc -std=c99 -Wall t7.11.c -o t7.11

.PHONY : clean
clean :  
		rm -rf t7.2 t7.3.1 t7.3.2 t7.4 t7.5 t7.5.1 t7.5.2 t7.8 t7.9 t7.10 t7.11
