.PHONY : ALL
ALL :  r11.4 t11.3 t11.4

r11.4:
	gcc -g -pthread -o r11.4 r11.4.c
t11.3:
	gcc -g -pthread -o t11.3 t11.3.c
t11.4:
	gcc -g -pthread -o t11.4 t11.4.c

.PHONY : clean
clean : 
	 rm -rf  r11.4 t11.3 t11.4
